#!/bin/bash

set -eo pipefail

cleanup() {
    pkill caddy || true
}

trap cleanup EXIT

readonly XCADDY="go run github.com/caddyserver/xcaddy/cmd/xcaddy"

$XCADDY list-modules

$XCADDY run -config test/Caddyfile.1&
pid="$!"
sleep 7
curl -v http://localhost:2015/ > output1
diff output1 test/test-1.ref
cleanup

$XCADDY run -config test/Caddyfile.2&
pid="$!"
sleep 7
curl -v http://localhost:2015/ > output2
diff output2 test/test-2.ref
cleanup

$XCADDY run -config test/Caddyfile.3&
pid="$!"
sleep 7
curl -v http://localhost:2015/ > output3_1
diff output3_1 test/test-3-1.ref
curl -v http://localhost:2015/test > output3_2
diff output3_2 test/test-3-2.ref
cleanup

$XCADDY run -config test/Caddyfile.4&
pid="$!"
sleep 7
curl -v http://localhost:2015/sjtug/caddy2-filter/master/test/test-4.input > output4
diff output4 test/test-4.ref
cleanup
