#!/bin/bash

set -eo pipefail

cleanup() {
    pkill caddy || true
}


# $1: path
# $2: additional flags
# Echos content
retry() {
    local cnt=0
    local -r THRES=10
    while ! curl -v $2 "http://localhost:2015${1}" > /tmp/response; do
        sleep 2
        cnt=${cnt}+1
        if [[ "$cnt" -gt "$THRES" ]]; then
            exit 1
        fi
    done
    cat /tmp/response
}

echobold() {
    local -r bold=$(tput bold)
    local -r normal=$(tput sgr0)
    echo "${bold}${1}${normal}"
}

trap cleanup EXIT

go get -v -u github.com/caddyserver/xcaddy/cmd/xcaddy
readonly XCADDY="go run github.com/caddyserver/xcaddy/cmd/xcaddy"

$XCADDY list-modules

echobold 'test case 1'
$XCADDY run -config test/Caddyfile.1&
pid="$!"
retry '/' > output1
diff output1 test/test-1.ref
cleanup

echobold 'test case 2'
$XCADDY run -config test/Caddyfile.2&
pid="$!"
retry '/' > output2
diff output2 test/test-2.ref
cleanup

echobold 'test case 3'
$XCADDY run -config test/Caddyfile.3&
pid="$!"
retry '/' > output3_1
diff output3_1 test/test-3-1.ref
retry '/test' > output3_2
diff output3_2 test/test-3-2.ref
cleanup

echobold 'test case 4'
$XCADDY run -config test/Caddyfile.4&
pid="$!"
retry '/sjtug/caddy2-filter/master/test/test-4.input' '--compressed' > output4
diff output4 test/test-4.ref
cleanup

echobold 'test case 5'
$XCADDY run -config test/Caddyfile.5&
pid="$!"
retry '/' > output5
diff output5 test/test-5.ref
cleanup

echobold 'test case 6'
$XCADDY run -config test/Caddyfile.6&
pid="$!"
retry '/' -i | grep -v Etag | grep -v Last-Modified | grep -v Date > output6
diff output6 test/test-6.ref
cleanup
